# configs/models.yaml
models:
  caption:
    blip2:
      model_name: "Salesforce/blip2-opt-2.7b"
      processor_name: "Salesforce/blip2-opt-2.7b"
      device_map: "auto"
      torch_dtype: "float16"
      enable_xformers: true

  vqa:
    llava:
      model_name: "llava-hf/llava-v1.6-mistral-7b-hf"
      processor_name: "llava-hf/llava-v1.6-mistral-7b-hf"
      device_map: "auto"
      torch_dtype: "float16"
      low_cpu_mem_usage: true

    qwen_vl:
      model_name: "Qwen/Qwen-VL-Chat"
      trust_remote_code: true
      device_map: "auto"
      torch_dtype: "float16"

  llm:
    qwen:
      model_name: "Qwen/Qwen2-7B-Instruct"
      tokenizer_name: "Qwen/Qwen2-7B-Instruct"
      device_map: "auto"
      torch_dtype: "float16"
      use_cache: true

    llama:
      model_name: "meta-llama/Llama-2-7b-chat-hf"
      tokenizer_name: "meta-llama/Llama-2-7b-chat-hf"
      device_map: "auto"
      torch_dtype: "float16"

  embeddings:
    bge:
      model_name: "BAAI/bge-m3"
      device_map: "auto"
      normalize_embeddings: true
